%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1920
image_height: 1080
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   fx: 1386.4139404296875
   fy: 1386.4139404296875
   cx: 960.0
   cy: 540.0
